#!/usr/bin/env python3

"""
========
list2dxf
========
-----------------------------------------------------------------------
Conversion of image heightfield to triangle mesh in Autodesk DXF format
-----------------------------------------------------------------------

Overview
--------

**list2dxf** export module present function for converting images
and image-like nested lists to 3D triangle mesh height field,
and saving mesh thus obtained in Autodesk ASCII DXF format
according to `AutoCAD 2012 DXF Reference`_.

Usage
-----

::

    list2dxf.list2dxf(image3d, maxcolors, result_file_name)

where:

- ``image3d``: image as list of lists of lists of int channel values;
- ``maxcolors``: maximum of channel value in ``image3d`` list (int),
  255 for 8 bit and 65535 for 16 bit input;
- ``result_file_name``: name of DXF file to export.

Reference
---------

Autodesk `AutoCAD 2012 DXF Reference`_, p. 64.

.. _AutoCAD 2012 DXF Reference: https://images.autodesk.com/adsk/files/autocad_2012_pdf_dxf-reference_enu.pdf

-------------------
Main site: `The Toad's Slimy Mudhole`_

.. _The Toad's Slimy Mudhole: https://dnyarri.github.io

img2mesh Git repositories: `img2mesh@Github`_, `img2mesh@Gitflic`_.

.. _img2mesh@Github: https://github.com/Dnyarri/img2mesh/tree/classic

.. _img2mesh@Gitflic: https://gitflic.ru/project/dnyarri/img2mesh?branch=classic

"""

__author__ = 'Ilya Razmanov'
__copyright__ = '(c) 2024-2026 Ilya Razmanov'
__credits__ = 'Ilya Razmanov'
__license__ = 'unlicense'
__version__ = '1.27.27.7'  # 27 Mar 2026
__maintainer__ = 'Ilya Razmanov'
__email__ = 'ilyarazmanov@gmail.com'
__status__ = 'Production'

from time import strftime

def list2dxf(image3d, maxcolors, resultfilename):
    """Convert image (nested 3D list of ``x``, ``y``, ``z`` coordinates)
    to Autodesk ASCII DXF triangle mesh.

    :param image3d: image as list of lists of lists of int channel values;
    :type image3d: list[list[list[int]]
    :param int maxcolors: maximum of channel value in ``image3d`` list (int),
        255 for 8 bit and 65535 for 16 bit input;
    :param str resultfilename: name of ASCII DXF file to export.

    """

    # ↓ Determining image size
    Y, X, Z = (len(image3d), len(image3d[0]), len(image3d[0][0]))

    """ ╔═══════════════╗
        ║ src functions ║
        ╚═══════════════╝ """

    def _pixel(x: int | float, y: int | float) -> list[int | float]:
        """Getting whole pixel from image list, force repeat edge
        instead of out of range. Returns list[channel,] for pixel(x, y).

        .. warning:: Coordinate system mirrored against Y!"""

        cx = min((X - 1), max(0, int(x)))
        cy = min((Y - 1), max(0, int(Y - 1 - y)))
        pixelvalue = image3d[cy][cx]
        return pixelvalue

    def _src_lum(x: int | float, y: int | float) -> float:
        """Returns brightness of pixel(x, y), multiplied by opacity if exists, normalized to 0..1 range."""

        if Z == 1:  # L
            l = _pixel(x, y)[0]
            return l / maxcolors
        if Z == 2:  # LA, multiply L by A. A = 0 is transparent, a = maxcolors is opaque
            l, a = _pixel(x, y)
            la = l * a / maxcolors
            return la / maxcolors
        if Z == 3:  # RGB
            r, g, b = _pixel(x, y)
            l = 0.298936021293775 * r + 0.587043074451121 * g + 0.114020904255103 * b
            return l / maxcolors
        if Z > 3:  # RGBA, multiply calculated L by A.
            r, g, b, a = _pixel(x, y)
            l = 0.298936021293775 * r + 0.587043074451121 * g + 0.114020904255103 * b
            la = l * a / maxcolors
            return la / maxcolors

    """ ╔══════════════════╗
        ║ Writing DXF file ║
        ╚══════════════════╝ """

    # ↓ Global positioning and scaling to tweak.
    X_OFFSET = -0.5 * (X - 1.0)  # To be added BEFORE rescaling to center object.
    Y_OFFSET = -0.5 * (Y - 1.0)  # To be added BEFORE rescaling to center object
    XY_RESCALE = 1.0 / (max(X, Y) - 1.0)  # To fit object into 1,1,1 cube

    def _x_out(x, shift):
        """Recalculate source x to result x."""
        return XY_RESCALE * (x + shift + X_OFFSET)

    def _y_out(y, shift):
        """Recalculate source y to result y."""
        return XY_RESCALE * (y + shift + Y_OFFSET)

    # ↓ Float output precision. Max for Python double is supposed to be 16, however
    #   for 16-bit images 7 is enough.
    PRECISION = '7f'

    resultfile = open(resultfilename, 'w')

    """ ┌────────────┐
        │ DXF header │
        └────────────┘ """
    resultfile.write(
        ''.join(
            [
                f'999\nGenerated by {f"{__name__}".rpartition(".")[2]} v. {__version__} at {strftime("%d %b %Y %H:%M:%S")}\n0\nSECTION\n2\nHEADER\n0\nENDSEC\n0\n',
                'SECTION\n2\nTABLES\n0\nTABLE\n2\nLAYER\n70\n5\n0\nLAYER\n2\nPRYANIK\n70\n0\n62\n1\n6\nCONTINUOUS\n0\nENDTAB\n0\nENDSEC\n0\n',
                'SECTION\n2\nENTITIES\n0\n',
            ]
        )
    )

    """ ┌──────┐
        │ Mesh │
        └──────┘ """

    v1 = v2 = v3 = v4 = 0.0  # Not needed for Python but Ruff gets mad without it.

    for y in range(Y - 1):
        row = []  # Starting a row of squares.
        for x in range(X - 1):
            if x > 0:
                v1 = v2
                v4 = v3
                v2 = _src_lum(x + 1, y)
                v3 = _src_lum(x + 1, y + 1)
            else:
                v1 = _src_lum(x, y)
                v2 = _src_lum(x + 1, y)
                v3 = _src_lum(x + 1, y + 1)
                v4 = _src_lum(x, y + 1)

            # ↓ Finally going to build a square!
            #   Triangles are described clockwise;
            #   remember of mirroring in `_pixel`.
            pyramid = []
            if abs(v1 - v3) > abs(v2 - v4):
                if (v1 + v2 + v4) > (0.5 / maxcolors):  # triangle 1-2-4
                    pyramid.extend(
                        [
                            '3DFACE\n8\nPRYANIK\n',
                            f'10\n{_x_out(x, 0):.{PRECISION}}\n20\n{_y_out(y, 0):.{PRECISION}}\n30\n{v1:.{PRECISION}}\n',
                            f'11\n{_x_out(x, 1):.{PRECISION}}\n21\n{_y_out(y, 0):.{PRECISION}}\n31\n{v2:.{PRECISION}}\n',
                            f'12\n{_x_out(x, 0):.{PRECISION}}\n22\n{_y_out(y, 1):.{PRECISION}}\n32\n{v4:.{PRECISION}}\n',
                            '62\n0\n0\n',
                        ]
                    )
                if (v2 + v3 + v4) > (0.5 / maxcolors):  # triangle 2-3-4
                    pyramid.extend(
                        [
                            '3DFACE\n8\nPRYANIK\n',
                            f'10\n{_x_out(x, 1):.{PRECISION}}\n20\n{_y_out(y, 0):.{PRECISION}}\n30\n{v2:.{PRECISION}}\n',
                            f'11\n{_x_out(x, 1):.{PRECISION}}\n21\n{_y_out(y, 1):.{PRECISION}}\n31\n{v3:.{PRECISION}}\n',
                            f'12\n{_x_out(x, 0):.{PRECISION}}\n22\n{_y_out(y, 1):.{PRECISION}}\n32\n{v4:.{PRECISION}}\n',
                            '62\n0\n0\n',
                        ]
                    )
            else:
                if (v1 + v2 + v3) > (0.5 / maxcolors):  # triangle 1-2-3
                    pyramid.extend(
                        [
                            '3DFACE\n8\nPRYANIK\n',
                            f'10\n{_x_out(x, 0):.{PRECISION}}\n20\n{_y_out(y, 0):.{PRECISION}}\n30\n{v1:.{PRECISION}}\n',
                            f'11\n{_x_out(x, 1):.{PRECISION}}\n21\n{_y_out(y, 0):.{PRECISION}}\n31\n{v2:.{PRECISION}}\n',
                            f'12\n{_x_out(x, 1):.{PRECISION}}\n22\n{_y_out(y, 1):.{PRECISION}}\n32\n{v3:.{PRECISION}}\n',
                            '62\n0\n0\n',
                        ]
                    )
                if (v1 + v3 + v4) > (0.5 / maxcolors):  # triangle 1-3-4
                    pyramid.extend(
                        [
                            '3DFACE\n8\nPRYANIK\n',
                            f'10\n{_x_out(x, 0):.{PRECISION}}\n20\n{_y_out(y, 0):.{PRECISION}}\n30\n{v1:.{PRECISION}}\n',
                            f'11\n{_x_out(x, 1):.{PRECISION}}\n21\n{_y_out(y, 1):.{PRECISION}}\n31\n{v3:.{PRECISION}}\n',
                            f'12\n{_x_out(x, 0):.{PRECISION}}\n22\n{_y_out(y, 1):.{PRECISION}}\n32\n{v4:.{PRECISION}}\n',
                            '62\n0\n0\n',
                        ]
                    )

            # ↓ Construction complete.
            #   Folded square completed and ready to place.
            #   AVE ME!
            row.extend(pyramid)
        # ↓ Flushing a row to file.
        resultfile.write(''.join(row))

    resultfile.write('ENDSEC\n0\nEOF\n')  # closing object

    # ↓ Close output
    resultfile.close()

    return None


# ↓ Procedure end, main body begins
if __name__ == '__main__':
    print('Module to be imported, not run as standalone')
