#!/usr/bin/env python3

"""
========
list2obj
========
------------------------------------------------------------------------
Conversion of image heightfield to triangle mesh in Wavefront OBJ format
------------------------------------------------------------------------

Overview
---------

**list2obj** export module present function for converting images
and image-like nested lists to 3D triangle mesh height field,
and saving mesh thus obtained in Wavefront OBJ format
according to `B1. Object Files (.obj)`_ specification.

Usage
-----

::

    list2obj.list2obj(image3d, maxcolors, result_file_name)

where:

- ``image3d``: image as list of lists of lists of int channel values;
- ``maxcolors``: maximum of channel value in ``image3d`` list (int),
  255 for 8 bit and 65535 for 16 bit input;
- ``result_file_name``: name of OBJ file to export.

Reference
---------

`B1. Object Files (.obj)`_.

.. _B1. Object Files (.obj): https://paulbourke.net/dataformats/obj/obj_spec.pdf

-------------------
Main site: `The Toad's Slimy Mudhole`_

.. _The Toad's Slimy Mudhole: https://dnyarri.github.io

img2mesh Git repositories: `img2mesh@Github`_, `img2mesh@Gitflic`_.

.. _img2mesh@Github: https://github.com/Dnyarri/img2mesh/tree/classic

.. _img2mesh@Gitflic: https://gitflic.ru/project/dnyarri/img2mesh?branch=classic

"""

__author__ = 'Ilya Razmanov'
__copyright__ = '(c) 2024-2026 Ilya Razmanov'
__credits__ = 'Ilya Razmanov'
__license__ = 'unlicense'
__version__ = '1.27.27.7'  # 27 Mar 2026
__maintainer__ = 'Ilya Razmanov'
__email__ = 'ilyarazmanov@gmail.com'
__status__ = 'Production'

from time import strftime

def list2obj(image3d, maxcolors, resultfilename):
    """Convert image (nested 3D list of ``x``, ``y``, ``z`` coordinates)
    to Wavefront OBJ triangle mesh.

    :param image3d: image as list of lists of lists of int channel values;
    :type image3d: list[list[list[int]]
    :param int maxcolors: maximum of channel value in ``image3d`` list (int),
        255 for 8 bit and 65535 for 16 bit input;
    :param str resultfilename: name of OBJ file to export.

    """

    # ↓ Determining image size
    Y, X, Z = (len(image3d), len(image3d[0]), len(image3d[0][0]))

    """ ╔═══════════════╗
        ║ src functions ║
        ╚═══════════════╝ """

    def _pixel(x, y):
        """Getting whole pixel from image list, force repeat edge
        instead of out of range. Returns list[channel,] for pixel(x, y).

        .. warning:: Coordinate system mirrored against Y!"""

        cx = min((X - 1), max(0, int(x)))
        cy = min((Y - 1), max(0, int(Y - 1 - y)))
        pixelvalue = image3d[cy][cx]
        return pixelvalue

    def _src_lum(x, y):
        """Returns brightness of pixel(x, y), multiplied by opacity if exists, normalized to 0..1 range."""

        if Z == 1:  # L
            l = _pixel(x, y)[0]
            return l / maxcolors
        if Z == 2:  # LA, multiply L by A. A = 0 is transparent, a = maxcolors is opaque
            l, a = _pixel(x, y)
            la = l * a / maxcolors
            return la / maxcolors
        if Z == 3:  # RGB
            r, g, b = _pixel(x, y)
            l = 0.298936021293775 * r + 0.587043074451121 * g + 0.114020904255103 * b
            return l / maxcolors
        if Z > 3:  # RGBA, multiply calculated L by A.
            r, g, b, a = _pixel(x, y)
            l = 0.298936021293775 * r + 0.587043074451121 * g + 0.114020904255103 * b
            la = l * a / maxcolors
            return la / maxcolors

    """ ╔══════════════════╗
        ║ Writing OBJ file ║
        ╚══════════════════╝ """

    # ↓ Global positioning and scaling to tweak.
    X_OFFSET = -0.5 * (X - 1.0)  # To be added BEFORE rescaling to center object.
    Y_OFFSET = -0.5 * (Y - 1.0)  # To be added BEFORE rescaling to center object
    XY_RESCALE = 1.0 / (max(X, Y) - 1.0)  # To fit object into 1,1,1 cube

    def _x_out(x, shift):
        """Recalculate source x to result x."""
        return XY_RESCALE * (x + shift + X_OFFSET)

    def _y_out(y, shift):
        """Recalculate source y to result y."""
        return XY_RESCALE * (y + shift + Y_OFFSET)

    # ↓ Float output precision. Max for Python double is supposed to be 16, however
    #   for 16-bit images 7 is enough.
    PRECISION = '7f'

    # ↓ Opening output file.
    resultfile = open(resultfilename, 'w')

    """ ╒════════════╕
        │ OBJ header │
        └────────────┘ """
    resultfile.write(f'# Generated by {f"{__name__}".rpartition(".")[2]} v. {__version__} at {strftime("%d %b %Y %H:%M:%S")}\n# Suggested axes: Z up, Y forward\n')

    resultfile.write('o pryanik_nepechatnyj\n')  # opening object

    """ ╒══════╕
        │ Mesh │
        └──────┘ """

    v1 = v2 = v3 = v4 = 0.0  # Not needed for Python but Ruff gets mad without it.

    for y in range(Y - 1):
        row = []  # Starting a row of squares.
        for x in range(X - 1):
            if x > 0:
                v1 = v2
                v4 = v3
                v2 = _src_lum(x + 1, y)
                v3 = _src_lum(x + 1, y + 1)
            else:
                v1 = _src_lum(x, y)
                v2 = _src_lum(x + 1, y)
                v3 = _src_lum(x + 1, y + 1)
                v4 = _src_lum(x, y + 1)

            # ↓ Finally going to build a square!
            #   Triangles are described clockwise;
            #   remember of mirroring in `_pixel`.
            pyramid = []

            if abs(v1 - v3) > abs(v2 - v4):
                if (v1 + v2 + v4) > (0.5 / maxcolors):  # triangle 1-2-4
                    pyramid.extend(
                        [
                            f'v {f"{_x_out(x, 0):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{_y_out(y, 0):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{v1:.{PRECISION}}".rstrip("0").rstrip(".")}\n',
                            f'v {f"{_x_out(x, 1):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{_y_out(y, 0):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{v2:.{PRECISION}}".rstrip("0").rstrip(".")}\n',
                            f'v {f"{_x_out(x, 0):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{_y_out(y, 1):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{v4:.{PRECISION}}".rstrip("0").rstrip(".")}\n',
                            'f -3 -2 -1\n',
                        ]
                    )  # ↑ triangle 1-2-4
                if (v2 + v3 + v4) > (0.5 / maxcolors):  # triangle 2-3-4
                    pyramid.extend(
                        [
                            f'v {f"{_x_out(x, 1):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{_y_out(y, 0):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{v2:.{PRECISION}}".rstrip("0").rstrip(".")}\n',
                            f'v {f"{_x_out(x, 1):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{_y_out(y, 1):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{v3:.{PRECISION}}".rstrip("0").rstrip(".")}\n',
                            f'v {f"{_x_out(x, 0):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{_y_out(y, 1):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{v4:.{PRECISION}}".rstrip("0").rstrip(".")}\n',
                            'f -3 -2 -1\n',
                        ]
                    )  # ↑ triangle 2-3-4
            else:
                if (v1 + v2 + v3) > (0.5 / maxcolors):  # triangle 1-2-3
                    pyramid.extend(
                        [
                            f'v {f"{_x_out(x, 0):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{_y_out(y, 0):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{v1:.{PRECISION}}".rstrip("0").rstrip(".")}\n',
                            f'v {f"{_x_out(x, 1):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{_y_out(y, 0):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{v2:.{PRECISION}}".rstrip("0").rstrip(".")}\n',
                            f'v {f"{_x_out(x, 1):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{_y_out(y, 1):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{v3:.{PRECISION}}".rstrip("0").rstrip(".")}\n',
                            'f -3 -2 -1\n',
                        ]
                    )  # ↑ triangle 1-2-3
                if (v1 + v3 + v4) > (0.5 / maxcolors):  # triangle 1-3-4
                    pyramid.extend(
                        [
                            f'v {f"{_x_out(x, 0):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{_y_out(y, 0):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{v1:.{PRECISION}}".rstrip("0").rstrip(".")}\n',
                            f'v {f"{_x_out(x, 1):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{_y_out(y, 1):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{v3:.{PRECISION}}".rstrip("0").rstrip(".")}\n',
                            f'v {f"{_x_out(x, 0):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{_y_out(y, 1):.{PRECISION}}".rstrip("0").rstrip(".")} {f"{v4:.{PRECISION}}".rstrip("0").rstrip(".")}\n',
                            'f -3 -2 -1\n',
                        ]
                    )  # ↑ triangle 1-3-4

            # ↓ Construction complete.
            #   Folded square completed and ready to place.
            #   AVE ME!
            row.extend(pyramid)
        # ↓ Flushing a row to file.
        resultfile.write(''.join(row))

    resultfile.write('# end pryanik_nepechatnyj')  # closing object

    # ↓ Closing output file.
    resultfile.close()

    return None


# ↓ Procedure end, main body begins
if __name__ == '__main__':
    print('Module to be imported, not run as standalone')
